package com.mycompany.myapp.domain.enumeration;

/**
 * The Status enumeration.
 */
public enum Status {
    WITHDRAWN, CARRIER_REJECTED, TENDER_BYPASSED, SPOTMARKET, OLD, EXPIRED, PENDING, LOAD_REMOVED, VOIDED, COMPLETED, ACCEPTED, SHIPPER_REJECTED, CANCELED, TENDERED, NO_OFFERS, REMOVED
}
