version: '2'
services:
  emulator-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/emulator/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=emulator
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
